services:
  app:
    container_name: productms
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/productdb
      DB_USERNAME: myuser
      DB_PASSWORD: secret
    networks:
      - productms-network

  postgres:
    container_name: productdb
    image: postgres:latest
    ports:
      - "5544:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: productdb
    networks:
      - productms-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  productms-network:

volumes:
  postgres-data: