version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'orders_db'
    ports:
      - '4000:3306'

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: 'jdbc:mysql://mysql:3306/orders_db'
      DB_PASSWORD: '123456'
      DB_USERNAME: 'root'
      STOCK_PRODUCTS_URL: 'http://localhost:8080'
      CUSTOMER_MANAGEMENT_URL: 'http://localhost:8081'
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - rabbitmq
    restart: always
