version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'customers_db'
    ports:
      - "4001:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
    environment:
      DB_URL: 'jdbc:mysql://mysql:3306/orders_db'
      DB_USERNAME: 'root'
      DB_PASSWORD: '123456'
    ports:
      - "8080:8080"